import type { Opportunity } from "./types";

export const REAL_SCHEMES: Opportunity[] = [
  {
    id: "nsp-post-matric",
    title: "National Scholarship Portal – Post Matric Scholarship",
    organization: "Ministry of Education, Government of India",
    category: "Scholarship",
    description:
      "Central and state-funded post-matric scholarships for SC, ST, OBC, and minority students pursuing higher education. Covers maintenance allowance and compulsory non-refundable fees through the National Scholarship Portal.",
    benefits: [
      "Maintenance allowance up to ₹1,200/month for hostellers",
      "Reimbursement of compulsory non-refundable fees",
      "Direct Benefit Transfer to bank accounts",
    ],
    eligibility: [
      "Indian national belonging to SC, ST, OBC, or notified minority community",
      "Annual family income below state-specific ceiling (typically ₹2.5–8 lakh)",
      "Enrolled in recognized post-matric course at a recognized institution",
      "Not receiving another government scholarship for the same purpose",
    ],
    documents: [
      "Aadhaar card",
      "Income certificate",
      "Caste or minority community certificate",
      "Previous year mark sheet",
      "Bank passbook or cancelled cheque",
      "Institution bonafide certificate",
    ],
    deadline: "2026-08-08",
    amount: "Up to ₹1,200/month + fee reimbursement",
    location: "Pan India",
    officialUrl: "https://scholarships.gov.in",
    verified: true,
    tags: ["scholarship", "post-matric", "SC", "ST", "OBC", "minority", "NSP"],
    applicationSteps: [
      "Register on scholarships.gov.in with Aadhaar-linked mobile number",
      "Complete student profile and academic details",
      "Select the applicable post-matric scheme for your category and state",
      "Upload required documents and submit before the deadline",
      "Track application status on NSP dashboard until verification by institute",
    ],
    commonMistakes: [
      "Selecting wrong state or scheme category leading to rejection",
      "Uploading expired income or caste certificates",
      "Missing institute verification before the cutoff date",
    ],
    faqs: [
      {
        question: "Can I apply for multiple NSP scholarships?",
        answer:
          "No. Students can avail only one scholarship under NSP for the same level of study in an academic year.",
      },
      {
        question: "When is the scholarship amount credited?",
        answer:
          "Amount is disbursed via DBT after institute and state nodal officer verification, typically within 2–4 months of approval.",
      },
    ],
    publishedAt: "2026-06-01",
  },
  {
    id: "nsp-pre-matric",
    title: "National Scholarship Portal – Pre Matric Scholarship",
    organization: "Ministry of Education, Government of India",
    category: "Scholarship",
    description:
      "Pre-matric scholarships for students of Classes 9 and 10 from SC, ST, OBC, and minority communities. Aims to reduce dropout rates by covering school-related expenses.",
    benefits: [
      "Scholarship amount of ₹225–750/month depending on class and category",
      "Ad hoc grant for disabled students up to ₹1,000/year",
      "DBT disbursement to student or parent bank account",
    ],
    eligibility: [
      "Student in Class 9 or 10 at a recognized government or private school",
      "Belongs to SC, ST, OBC, or notified minority community",
      "Annual family income below scheme-specific limit (typically ₹1–2.5 lakh)",
      "Minimum 50% marks in previous class (relaxation for fresh entrants)",
    ],
    documents: [
      "Aadhaar card",
      "Income certificate",
      "Caste or minority certificate",
      "Previous class mark sheet",
      "School bonafide certificate",
      "Bank account details",
    ],
    deadline: "2026-08-12",
    amount: "₹225–750/month",
    location: "Pan India",
    officialUrl: "https://scholarships.gov.in",
    verified: true,
    tags: ["scholarship", "pre-matric", "class-9", "class-10", "NSP"],
    applicationSteps: [
      "Create account on National Scholarship Portal",
      "Fill pre-matric application with school and category details",
      "Upload income and caste or minority certificates",
      "Submit application and note application ID",
      "Ensure school verifies the application on NSP before deadline",
    ],
    commonMistakes: [
      "Applying after school verification window closes",
      "Entering incorrect class or roll number details",
      "Using parent bank account without linking to Aadhaar for DBT",
    ],
    faqs: [
      {
        question: "Is there a minimum attendance requirement?",
        answer:
          "Yes. Students must maintain at least 75% attendance as certified by the school to remain eligible.",
      },
    ],
    publishedAt: "2026-06-01",
  },
  {
    id: "csss-college",
    title: "Central Sector Scheme of Scholarship for College and University Students",
    organization: "Ministry of Education, Department of Higher Education",
    category: "Scholarship",
    description:
      "Merit-based scholarship for top-performing students from economically weaker sections pursuing undergraduate and postgraduate degrees at recognized colleges and universities.",
    benefits: [
      "₹12,000 per year for undergraduate students",
      "₹20,000 per year for postgraduate students",
      "Renewable annually based on academic performance",
    ],
    eligibility: [
      "Indian citizen with family income below ₹8 lakh per annum",
      "Secured above 80th percentile in relevant stream in Class 12 board exam",
      "Pursuing regular degree course at recognized college or university",
      "Not availing any other government scholarship for the same course",
    ],
    documents: [
      "Aadhaar card",
      "Income certificate",
      "Class 12 mark sheet",
      "College admission proof",
      "Bank passbook",
      "Passport-size photograph",
    ],
    deadline: "2026-08-15",
    amount: "₹12,000–20,000/year",
    location: "Pan India",
    officialUrl: "https://scholarships.gov.in",
    verified: true,
    tags: ["scholarship", "merit", "college", "UG", "PG", "CSSS"],
    applicationSteps: [
      "Register on NSP and select Central Sector Scheme of Scholarship",
      "Enter Class 12 percentile and income details accurately",
      "Upload mark sheet and income certificate",
      "Submit and track verification by institute nodal officer",
      "Renew application each academic year with updated marks",
    ],
    commonMistakes: [
      "Incorrectly claiming 80th percentile without board data verification",
      "Failing to renew scholarship in subsequent years",
      "Applying while enrolled in distance or correspondence courses (not eligible)",
    ],
    faqs: [
      {
        question: "How is the 80th percentile determined?",
        answer:
          "It is calculated based on Class 12 board results for the relevant stream (Science, Commerce, Arts) as published by CBSE or respective state boards.",
      },
    ],
    publishedAt: "2026-06-01",
  },
  {
    id: "aicte-pragati",
    title: "AICTE Pragati Scholarship for Girl Students",
    organization: "All India Council for Technical Education (AICTE)",
    category: "Scholarship",
    description:
      "Scholarship scheme to support girl students pursuing technical diploma or degree programs in AICTE-approved institutions. Promotes women participation in technical education.",
    benefits: [
      "₹50,000 per year as tuition fee reimbursement",
      "₹2,000 per month for 10 months as incidental charges",
      "Total annual benefit up to ₹70,000",
    ],
    eligibility: [
      "Girl student admitted to 1st year of AICTE-approved diploma or degree program",
      "Family annual income not exceeding ₹8 lakh",
      "Only one girl per family can avail the scholarship",
      "Must not be receiving any other AICTE scholarship simultaneously",
    ],
    documents: [
      "Aadhaar card",
      "Income certificate",
      "Admission letter from AICTE-approved institute",
      "Tuition fee receipt",
      "Bank account details",
      "Passport-size photograph",
    ],
    deadline: "2026-08-18",
    amount: "Up to ₹70,000/year",
    location: "Pan India",
    officialUrl: "https://www.aicte-india.org/schemes/students-development-schemes",
    verified: true,
    tags: ["scholarship", "women", "engineering", "AICTE", "diploma", "degree"],
    applicationSteps: [
      "Visit AICTE scholarship portal or NSP for Pragati scheme",
      "Register with academic and family income details",
      "Upload admission proof and fee receipts from AICTE institute",
      "Submit application within the academic year window",
      "Await institute verification and AICTE approval for disbursement",
    ],
    commonMistakes: [
      "Applying from non-AICTE-approved institutions",
      "Multiple girl students from same family applying (only one allowed)",
      "Submitting incomplete tuition fee documentation",
    ],
    faqs: [
      {
        question: "Can lateral-entry students apply?",
        answer:
          "Yes, girl students admitted through lateral entry to 2nd year in AICTE-approved programs are eligible if they meet income and other criteria.",
      },
    ],
    publishedAt: "2026-06-01",
  },
  {
    id: "aicte-saksham",
    title: "AICTE Saksham Scholarship for Differently Abled Students",
    organization: "All India Council for Technical Education (AICTE)",
    category: "Scholarship",
    description:
      "Financial assistance for differently abled students pursuing technical diploma or degree courses in AICTE-approved institutions across India.",
    benefits: [
      "₹50,000 per year tuition fee reimbursement",
      "₹2,000 per month for 10 months as incidental allowance",
      "Total annual support up to ₹70,000",
    ],
    eligibility: [
      "Differently abled student with 40% or more disability certificate",
      "Admitted to 1st year diploma or degree in AICTE-approved institution",
      "Family annual income below ₹8 lakh",
      "Not availing another AICTE scholarship for the same course",
    ],
    documents: [
      "Disability certificate (40% or above)",
      "Aadhaar card",
      "Income certificate",
      "Admission letter from AICTE institute",
      "Tuition fee receipt",
      "Bank account details",
    ],
    deadline: "2026-08-22",
    amount: "Up to ₹70,000/year",
    location: "Pan India",
    officialUrl: "https://www.aicte-india.org/schemes/students-development-schemes",
    verified: true,
    tags: ["scholarship", "disability", "AICTE", "technical education"],
    applicationSteps: [
      "Access AICTE Saksham scheme on the official portal or NSP",
      "Register with disability and academic credentials",
      "Upload disability certificate and institute admission proof",
      "Complete application and submit before deadline",
      "Track verification status through institute nodal officer",
    ],
    commonMistakes: [
      "Submitting disability certificate below 40% threshold",
      "Applying without valid UDID or government disability certificate",
      "Missing institute-level verification step",
    ],
    faqs: [
      {
        question: "Is UDID mandatory for Saksham?",
        answer:
          "A valid disability certificate issued by competent medical authority is required; UDID is recommended and increasingly accepted as standard proof.",
      },
    ],
    publishedAt: "2026-06-01",
  },
  {
    id: "nmms",
    title: "National Means-cum-Merit Scholarship (NMMS)",
    organization: "Ministry of Education, Department of School Education & Literacy",
    category: "Scholarship",
    description:
      "Centrally sponsored scholarship for meritorious students from economically weaker sections to continue studies from Class 9 through Class 12 and reduce dropout at secondary level.",
    benefits: [
      "₹12,000 per year (₹1,000 per month)",
      "Scholarship continues for 4 years (Classes 9–12)",
      "Direct bank transfer upon state-level selection",
    ],
    eligibility: [
      "Student studying in Class 8 in a government or aided school",
      "Minimum 55% marks in Class 7 (50% for SC/ST students)",
      "Annual family income not exceeding ₹3.5 lakh",
      "Must qualify state-level NMMS examination",
    ],
    documents: [
      "Aadhaar card",
      "Income certificate",
      "Class 7 mark sheet",
      "School bonafide certificate",
      "Caste certificate if applicable",
      "Bank account details",
    ],
    deadline: "2026-08-28",
    amount: "₹12,000/year",
    location: "Pan India",
    officialUrl: "https://scholarships.gov.in",
    verified: true,
    tags: ["scholarship", "NMMS", "class-8", "merit-cum-means", "school"],
    applicationSteps: [
      "Appear for state-conducted NMMS examination in Class 8",
      "Qualify based on merit and income criteria set by state",
      "Register on NSP after selection and upload required documents",
      "Submit scholarship application with examination qualification proof",
      "Renew annually with academic progress certificate until Class 12",
    ],
    commonMistakes: [
      "Missing the state-level NMMS exam registration deadline",
      "Failing to renew scholarship annually with required marks (55%)",
      "Applying without qualifying the NMMS examination first",
    ],
    faqs: [
      {
        question: "What is the NMMS exam pattern?",
        answer:
          "The exam typically has Mental Ability Test (MAT) and Scholastic Aptitude Test (SAT) sections, conducted by respective state/UT education departments.",
      },
    ],
    publishedAt: "2026-06-01",
  },
  {
    id: "pg-indira-gandhi-sgc",
    title: "Post Graduate Indira Gandhi Scholarship for Single Girl Child",
    organization: "University Grants Commission (UGC)",
    category: "Scholarship",
    description:
      "UGC scholarship for a single girl child pursuing postgraduate studies in universities and colleges recognized under Section 2(f) and 12(B) of the UGC Act.",
    benefits: [
      "₹36,200 per year for two years of postgraduate study",
      "Covers tuition and living expenses",
      "Awarded for full duration of PG program (max 2 years)",
    ],
    eligibility: [
      "Only girl child of the family (no brother or sister)",
      "Admitted to 1st year of full-time PG program in UGC-recognized institution",
      "Age limit: maximum 30 years at time of admission",
      "Not employed and not receiving any other UGC scholarship",
    ],
    documents: [
      "Aadhaar card",
      "Affidavit confirming single girl child status",
      "PG admission letter",
      "Undergraduate degree certificate and mark sheets",
      "Bank account details",
      "Passport-size photograph",
    ],
    deadline: "2026-08-31",
    amount: "₹36,200/year",
    location: "Pan India",
    officialUrl: "https://www.ugc.gov.in/sgc",
    verified: true,
    tags: ["scholarship", "women", "PG", "single-girl-child", "UGC"],
    applicationSteps: [
      "Check UGC notification for application window on ugc.gov.in",
      "Register on UGC scholarship portal with PG admission details",
      "Upload single girl child affidavit and academic documents",
      "Submit application before the notified deadline",
      "Track selection list published by UGC on official website",
    ],
    commonMistakes: [
      "Applying without notarized single girl child affidavit",
      "Applying when a sibling exists (including step-siblings in some interpretations)",
      "Submitting application for part-time or distance PG programs",
    ],
    faqs: [
      {
        question: "Are twin daughters eligible?",
        answer:
          "In case of twin girls with no other siblings, both may be considered eligible as per UGC guidelines; check current notification for specifics.",
      },
    ],
    publishedAt: "2026-06-01",
  },
  {
    id: "national-overseas-scholarship",
    title: "National Overseas Scholarship for SC/ST Students",
    organization: "Ministry of Social Justice and Empowerment",
    category: "Scholarship",
    description:
      "Financial support for SC and ST students to pursue master's and PhD degrees at accredited foreign universities. Covers tuition, living expenses, and travel.",
    benefits: [
      "Full tuition fee reimbursement up to prescribed limits",
      "Annual maintenance allowance for living expenses abroad",
      "Economy class air fare and visa fees covered",
      "Contingency and equipment allowance for research students",
    ],
    eligibility: [
      "Indian national belonging to SC or ST category",
      "Family income below ₹8 lakh per annum",
      "Secured admission to accredited foreign university for Masters or PhD",
      "Age below 35 years for Masters and below 40 for PhD",
      "Minimum 60% marks in qualifying degree",
    ],
    documents: [
      "Caste certificate (SC/ST)",
      "Income certificate",
      "Foreign university admission letter",
      "IELTS, GRE, or TOEFL score reports as applicable",
      "Passport copy",
      "Academic transcripts and degree certificates",
    ],
    deadline: "2026-09-05",
    amount: "Full tuition + living allowance abroad",
    location: "Pan India",
    officialUrl: "https://nosmsje.gov.in",
    verified: true,
    tags: ["scholarship", "overseas", "SC", "ST", "masters", "PhD", "foreign"],
    applicationSteps: [
      "Secure unconditional admission from accredited foreign institution",
      "Register on nosmsje.gov.in during application window",
      "Upload admission letter, academic records, and caste certificate",
      "Submit income proof and passport details",
      "Attend interview if shortlisted and await final selection by ministry",
    ],
    commonMistakes: [
      "Applying without confirmed foreign university admission",
      "Selecting non-accredited or blacklisted institutions",
      "Missing the annual application window (typically once per year)",
    ],
    faqs: [
      {
        question: "Which countries are covered?",
        answer:
          "Scholarships are available for studies in accredited universities in countries like USA, UK, Canada, Australia, Germany, and others as per ministry guidelines.",
      },
    ],
    publishedAt: "2026-06-01",
  },
  {
    id: "pm-internship",
    title: "PM Internship Scheme",
    organization: "Ministry of Corporate Affairs, Government of India",
    category: "Internship",
    description:
      "Flagship internship program placing youth in top 500 companies for 12 months of on-the-job training. Aims to provide real-world corporate experience to 1 crore young Indians over five years.",
    benefits: [
      "₹5,000 per month stipend for 12 months",
      "One-time grant of ₹6,000 for incidentals",
      "Insurance coverage during internship period",
      "Certificate and potential employment opportunities",
    ],
    eligibility: [
      "Indian citizen aged 21–24 years as on application date",
      "Not currently employed full-time or enrolled in full-time education",
      "Family income below ₹8 lakh per annum",
      "Completed at least secondary education (Class 10 or above)",
    ],
    documents: [
      "Aadhaar card",
      "Income certificate or self-declaration",
      "Educational qualification certificates",
      "Bank account details linked to Aadhaar",
      "Passport-size photograph",
    ],
    deadline: "2026-09-10",
    amount: "₹5,000/month + ₹6,000 one-time",
    location: "Pan India",
    officialUrl: "https://pminternship.mca.gov.in",
    verified: true,
    tags: ["internship", "corporate", "youth", "stipend", "PM"],
    applicationSteps: [
      "Register on pminternship.mca.gov.in with Aadhaar and mobile OTP",
      "Complete profile with education and income details",
      "Browse and apply to available internship positions at partner companies",
      "Attend company interview or selection process if shortlisted",
      "Accept offer and begin 12-month internship with monthly stipend",
    ],
    commonMistakes: [
      "Applying while enrolled in full-time degree program",
      "Not linking bank account for DBT stipend disbursement",
      "Missing company-specific application deadlines within the portal",
    ],
    faqs: [
      {
        question: "Is the internship paid?",
        answer:
          "Yes. Selected interns receive ₹5,000 per month for 12 months plus a one-time ₹6,000 grant, disbursed via Direct Benefit Transfer.",
      },
      {
        question: "Can I choose my preferred company?",
        answer:
          "You can apply to multiple companies listed on the portal; final placement depends on company selection criteria and availability.",
      },
    ],
    publishedAt: "2026-06-01",
  },
  {
    id: "ncs-internship",
    title: "National Career Service – Internship Portal",
    organization: "Ministry of Labour & Employment, Directorate General of Employment",
    category: "Internship",
    description:
      "NCS portal connects job seekers with internship opportunities across government, public sector, and private organizations. Provides a unified platform for internship discovery and application.",
    benefits: [
      "Access to thousands of internship listings nationwide",
      "Free registration and career counselling services",
      "Skill matching based on qualification and interests",
      "Certificates and experience letters from host organizations",
    ],
    eligibility: [
      "Indian citizen registered on National Career Service portal",
      "Minimum qualification as specified by individual internship posting",
      "Age criteria defined by each employer (typically 18–30 years)",
      "Valid email and mobile number for communication",
    ],
    documents: [
      "Aadhaar card",
      "Resume or CV",
      "Educational certificates",
      "Passport-size photograph",
      "Identity proof",
    ],
    deadline: "2026-09-15",
    amount: "Varies by employer",
    location: "Pan India",
    officialUrl: "https://www.ncs.gov.in",
    verified: true,
    tags: ["internship", "NCS", "career", "employment", "job-seeker"],
    applicationSteps: [
      "Register as job seeker on ncs.gov.in",
      "Complete profile with skills, education, and preferences",
      "Search internships under the Internship section",
      "Apply to relevant postings with updated resume",
      "Follow up with employer and attend interviews as scheduled",
    ],
    commonMistakes: [
      "Incomplete profile reducing match quality with employers",
      "Applying without tailoring resume to internship requirements",
      "Ignoring employer response emails or interview invitations",
    ],
    faqs: [
      {
        question: "Are NCS internships paid?",
        answer:
          "Stipend depends on the host organization; each listing specifies whether the internship is paid, unpaid, or offers a nominal allowance.",
      },
    ],
    publishedAt: "2026-06-01",
  },
  {
    id: "ugc-net-jrf",
    title: "UGC NET Junior Research Fellowship (JRF)",
    organization: "University Grants Commission / National Testing Agency",
    category: "Research",
    description:
      "National eligibility test for Assistant Professor and Junior Research Fellowship. Qualified JRF candidates receive fellowship to pursue PhD research at universities and research institutions.",
    benefits: [
      "JRF fellowship of ₹37,000 per month for first two years",
      "SRF of ₹42,000 per month after two years upon upgrade",
      "Annual contingency grant of ₹10,000–25,000 for research expenses",
      "Eligibility for Assistant Professor positions nationwide",
    ],
    eligibility: [
      "Master's degree with at least 55% marks (50% for SC/ST/OBC/PwD)",
      "Age limit: 31 years for JRF (relaxation for reserved categories)",
      "Must qualify UGC NET with JRF award in relevant subject",
      "Enrolled or seeking enrollment in PhD at UGC-recognized institution",
    ],
    documents: [
      "UGC NET scorecard with JRF award",
      "Postgraduate degree certificate and mark sheets",
      "Aadhaar card",
      "Caste certificate if applicable",
      "Research proposal for PhD enrollment",
      "No Objection Certificate from employer if employed",
    ],
    deadline: "2026-09-20",
    amount: "₹37,000–42,000/month",
    location: "Pan India",
    officialUrl: "https://ugcnet.nta.nic.in",
    verified: true,
    tags: ["research", "JRF", "PhD", "UGC NET", "fellowship", "academia"],
    applicationSteps: [
      "Register and appear for UGC NET examination on ugcnet.nta.nic.in",
      "Qualify with JRF award in your subject paper",
      "Secure PhD admission at UGC-recognized university within 2 years",
      "Activate JRF through university research section",
      "Submit annual progress reports to continue fellowship",
    ],
    commonMistakes: [
      "Missing JRF activation deadline (within 2 years of NET result)",
      "Confusing NET qualification (Assistant Professor only) with JRF award",
      "Not maintaining required research progress for fellowship continuation",
    ],
    faqs: [
      {
        question: "How long is JRF valid?",
        answer:
          "JRF is valid for 2 years from the date of NET result for PhD enrollment. After enrollment, fellowship continues for up to 5 years total including SRF period.",
      },
    ],
    publishedAt: "2026-06-01",
  },
  {
    id: "inspire-fellowship",
    title: "INSPIRE Fellowship (DST)",
    organization: "Department of Science & Technology, Government of India",
    category: "Research",
    description:
      "Innovation in Science Pursuit for Inspired Research fellowship supports meritorious students for doctoral research in basic and applied sciences at recognized institutions across India.",
    benefits: [
      "Fellowship of ₹31,000 per month for first two years",
      "₹35,000 per month for subsequent years",
      "Research contingency grant of ₹20,000 per year",
      "Access to DST research network and conferences",
    ],
    eligibility: [
      "First rank holder in PG examination from recognized university",
      "Or INSPIRE Scholar who secured minimum 65% in aggregate in PG",
      "Age below 27 years (relaxation for reserved categories)",
      "Admission to PhD in science or related field at recognized institution",
    ],
    documents: [
      "PG degree certificate with first rank proof or INSPIRE Scholar certificate",
      "PhD admission letter from recognized university",
      "Aadhaar card",
      "Research proposal",
      "Caste certificate if applicable",
      "Bank account details",
    ],
    deadline: "2026-09-25",
    amount: "₹31,000–35,000/month",
    location: "Pan India",
    officialUrl: "https://www.online-inspire.gov.in",
    verified: true,
    tags: ["research", "INSPIRE", "DST", "PhD", "science", "fellowship"],
    applicationSteps: [
      "Register on online-inspire.gov.in fellowship portal",
      "Submit application with PG marks and PhD admission proof",
      "Upload research proposal endorsed by PhD supervisor",
      "Await DST review and selection notification",
      "Activate fellowship upon selection through host institution",
    ],
    commonMistakes: [
      "Applying without confirmed PhD admission",
      "Missing the annual application deadline (typically August)",
      "Submitting research proposal not aligned with INSPIRE science domains",
    ],
    faqs: [
      {
        question: "Can engineering graduates apply for INSPIRE Fellowship?",
        answer:
          "Yes, if pursuing PhD in science or interdisciplinary research areas and meeting the merit criteria specified by DST.",
      },
    ],
    publishedAt: "2026-06-01",
  },
  {
    id: "sih-2026",
    title: "Smart India Hackathon 2026",
    organization: "Ministry of Education, AICTE & i4c",
    category: "Hackathon",
    description:
      "World's largest open innovation model connecting students with government ministries and industries to solve real-world problems through 36-hour hackathons at national and software editions.",
    benefits: [
      "Cash prizes up to ₹1 lakh for winning teams per problem statement",
      "Opportunity to implement solution with sponsoring ministry or industry",
      "Certificates and national recognition for all participants",
      "Internship and placement opportunities with partner organizations",
    ],
    eligibility: [
      "Team of 6 students from recognized Indian college or university",
      "At least one female member required in each team",
      "All team members must be currently enrolled students",
      "Faculty mentor mandatory for each participating team",
    ],
    documents: [
      "College ID cards of all team members",
      "Faculty mentor authorization letter",
      "Team registration on SIH portal",
      "Institute NODAL officer approval",
      "Aadhaar or identity proof",
    ],
    deadline: "2026-09-30",
    amount: "Up to ₹1 lakh per winning team",
    location: "Pan India",
    officialUrl: "https://www.sih.gov.in",
    verified: true,
    tags: ["hackathon", "innovation", "SIH", "students", "coding", "startup"],
    applicationSteps: [
      "Form team of 6 with faculty mentor at your institution",
      "Register institute and team on sih.gov.in",
      "Browse problem statements from ministries and industries",
      "Submit solution proposal for selected problem statement",
      "Participate in 36-hour grand finale if shortlisted",
    ],
    commonMistakes: [
      "Registering team without mandatory female member",
      "Selecting problem statement without reading full requirements",
      "Missing institute-level nodal officer approval before submission",
    ],
    faqs: [
      {
        question: "What is the difference between SIH Hardware and Software editions?",
        answer:
          "Hardware edition focuses on IoT and embedded solutions; Software edition targets software applications, AI, and data solutions for government problem statements.",
      },
    ],
    publishedAt: "2026-06-01",
  },
  {
    id: "startup-india-seed",
    title: "Startup India Seed Fund Scheme (SISFS)",
    organization: "Department for Promotion of Industry and Internal Trade (DPIIT)",
    category: "Startup Grant",
    description:
      "Government scheme providing seed funding to early-stage startups through empanelled incubators. Supports proof of concept, prototype development, product trials, and market entry.",
    benefits: [
      "Grants up to ₹20 lakh for validation, PoC, and prototype development",
      "Investments up to ₹50 lakh via debt or convertible debentures for market entry",
      "Mentorship through DPIIT-recognized incubators",
      "Access to Startup India network and investor connect",
    ],
    eligibility: [
      "DPIIT-recognized startup incorporated less than 2 years ago",
      "Startup must be working on innovative product or service with market fit",
      "Applied through a DPIIT-recognized incubator empanelled under SISFS",
      "Indian promoter shareholding of at least 51%",
    ],
    documents: [
      "DPIIT startup recognition certificate",
      "Certificate of incorporation",
      "Pitch deck and business plan",
      "Founder KYC and PAN",
      "Audited or provisional financial statements",
      "Patent or IP documentation if applicable",
    ],
    deadline: "2026-10-05",
    amount: "Up to ₹50 lakh",
    location: "Pan India",
    officialUrl: "https://www.startupindia.gov.in/content/sih/en/startup-schemes.html",
    verified: true,
    tags: ["startup", "seed-fund", "DPIIT", "incubator", "entrepreneurship"],
    applicationSteps: [
      "Obtain DPIIT startup recognition via startupindia.gov.in",
      "Identify and apply to an empanelled incubator under SISFS",
      "Submit pitch deck, business plan, and financial projections",
      "Present before incubator seed fund management committee",
      "Receive grant or investment upon approval with milestone-based disbursement",
    ],
    commonMistakes: [
      "Applying without DPIIT recognition certificate",
      "Approaching non-empanelled incubators for SISFS funding",
      "Unrealistic valuation or unclear use-of-funds in application",
    ],
    faqs: [
      {
        question: "Is equity dilution required for seed fund?",
        answer:
          "Grant component (up to ₹20 lakh) does not require equity dilution. Investment component (up to ₹50 lakh) may involve convertible instruments as per incubator terms.",
      },
    ],
    publishedAt: "2026-06-01",
  },
  {
    id: "mudra-pmmy",
    title: "Pradhan Mantri Mudra Yojana (PMMY)",
    organization: "Ministry of Finance, Micro Units Development & Refinance Agency (MUDRA)",
    category: "Startup Grant",
    description:
      "Collateral-free loans up to ₹10 lakh for non-corporate, non-farm small and micro enterprises. Supports small business owners, shopkeepers, and artisans to start or expand ventures.",
    benefits: [
      "Shishu loans up to ₹50,000 for new micro enterprises",
      "Kishore loans from ₹50,001 to ₹5 lakh for growing businesses",
      "Tarun loans from ₹5,00,001 to ₹10 lakh for established micro units",
      "No collateral required; refinance through MUDRA to banks",
    ],
    eligibility: [
      "Indian citizen with non-farm income-generating micro enterprise",
      "Business activity in manufacturing, trading, or services sector",
      "Credit need up to ₹10 lakh",
      "No defaulter to any bank or financial institution",
    ],
    documents: [
      "Aadhaar card and PAN",
      "Business proof or project report",
      "Identity and address proof",
      "Bank statements (6 months if existing business)",
      "Passport-size photographs",
      "Quotations for machinery or equipment if applicable",
    ],
    deadline: "2026-10-12",
    amount: "Up to ₹10 lakh",
    location: "Pan India",
    officialUrl: "https://www.mudra.org.in",
    verified: true,
    tags: ["loan", "MUDRA", "MSME", "micro-enterprise", "collateral-free"],
    applicationSteps: [
      "Prepare a simple business plan or project report",
      "Visit any scheduled commercial bank, RRB, cooperative bank, or NBFC-MFI",
      "Fill PMMY loan application form (Shishu, Kishore, or Tarun category)",
      "Submit KYC and business documents to the lending branch",
      "Receive loan sanction and MUDRA card upon approval",
    ],
    commonMistakes: [
      "Applying for amount exceeding actual business need (affects approval)",
      "Not having a clear business plan for first-time borrowers",
      "Approaching lenders without basic KYC documents ready",
    ],
    faqs: [
      {
        question: "What is the interest rate for Mudra loans?",
        answer:
          "Interest rates are set by individual lending banks, typically ranging from 8% to 12% per annum depending on the loan category and borrower profile.",
      },
    ],
    publishedAt: "2026-06-01",
  },
  {
    id: "stand-up-india",
    title: "Stand-Up India Scheme",
    organization: "Ministry of Finance, Department of Financial Services",
    category: "Startup Grant",
    description:
      "Facilitates bank loans between ₹10 lakh and ₹1 crore to at least one SC/ST borrower and one woman borrower per bank branch for greenfield enterprises in manufacturing, services, or trading.",
    benefits: [
      "Composite loan from ₹10 lakh to ₹1 crore",
      "Covers term loan and working capital requirements",
      "Handholding support through Stand-Up Mitra portal",
      "Convergence with other government schemes for additional support",
    ],
    eligibility: [
      "SC, ST, or woman entrepreneur above 18 years",
      "Setting up greenfield enterprise (first-time venture in activity)",
      "Enterprise in manufacturing, services, or trading sector",
      "Borrower should not be defaulter to any bank",
    ],
    documents: [
      "Aadhaar card and PAN",
      "Caste certificate for SC/ST applicants",
      "Project report with cost and means of finance",
      "Identity and address proof",
      "Educational qualification certificates",
      "Property documents if offering collateral",
    ],
    deadline: "2026-10-18",
    amount: "₹10 lakh – ₹1 crore",
    location: "Pan India",
    officialUrl: "https://www.standupmitra.in",
    verified: true,
    tags: ["startup", "women", "SC", "ST", "bank-loan", "entrepreneurship"],
    applicationSteps: [
      "Register on standupmitra.in and connect with lead district manager",
      "Prepare detailed project report for proposed enterprise",
      "Approach scheduled commercial bank branch with application",
      "Complete loan appraisal and submit required documents",
      "Receive sanction and begin enterprise upon loan disbursement",
    ],
    commonMistakes: [
      "Applying for expansion of existing business (only greenfield eligible)",
      "Incomplete project report leading to loan rejection",
      "Not utilizing Stand-Up Mitra handholding for application guidance",
    ],
    faqs: [
      {
        question: "Is collateral mandatory for Stand-Up India?",
        answer:
          "Loans up to ₹10 lakh may be covered under CGTMSE guarantee without collateral; higher amounts may require security as per bank policy.",
      },
    ],
    publishedAt: "2026-06-01",
  },
  {
    id: "udyam-msme",
    title: "Udyam Registration & MSME Support",
    organization: "Ministry of MSME, Government of India",
    category: "Startup Grant",
    description:
      "Free online Udyam Registration for micro, small, and medium enterprises. Registered MSMEs access priority sector lending, subsidies, tender preferences, and schemes like PMEGP and CLCSS.",
    benefits: [
      "Free Udyam Registration certificate with permanent registration number",
      "Priority sector lending and collateral-free loans up to ₹2 crore under CGTMSE",
      "25% subsidy on patent registration and ISO certification fees",
      "Exemption from earnest money deposit in government tenders",
    ],
    eligibility: [
      "Micro, small, or medium enterprise as per MSME classification norms",
      "Investment and turnover within revised MSME limits",
      "Valid Aadhaar of proprietor, partner, or director",
      "Valid PAN of enterprise and authorized signatory",
    ],
    documents: [
      "Aadhaar card of owner or authorized signatory",
      "PAN card of enterprise",
      "GST registration (if applicable)",
      "Bank account details",
      "NIC code for business activity",
    ],
    deadline: "2026-10-25",
    amount: "Subsidies up to 25% on select costs",
    location: "Pan India",
    officialUrl: "https://udyamregistration.gov.in",
    verified: true,
    tags: ["MSME", "Udyam", "registration", "small-business", "subsidy"],
    applicationSteps: [
      "Visit udyamregistration.gov.in and click 'For New Entrepreneurs'",
      "Enter Aadhaar and validate with OTP",
      "Fill enterprise details including PAN, activity, and investment",
      "Submit application and receive Udyam Registration certificate instantly",
      "Apply for linked schemes like PMEGP or CLCSS using Udyam number",
    ],
    commonMistakes: [
      "Entering incorrect investment or turnover figures",
      "Using personal PAN instead of enterprise PAN",
      "Not updating Udyam registration when enterprise graduates to higher category",
    ],
    faqs: [
      {
        question: "Is Udyam Registration mandatory for MSME benefits?",
        answer:
          "Yes. Udyam Registration replaced Udyog Aadhaar and is mandatory to avail government MSME schemes, subsidies, and tender benefits.",
      },
    ],
    publishedAt: "2026-06-01",
  },
  {
    id: "wep-women",
    title: "Women Entrepreneurship Platform (WEP)",
    organization: "NITI Aayog, Government of India",
    category: "Women Scheme",
    description:
      "NITI Aayog's unified access portal for women entrepreneurs providing incubation support, mentorship, market linkages, and information on government schemes tailored for women-led businesses.",
    benefits: [
      "Free access to mentorship from industry leaders",
      "Networking with investors and incubators",
      "Information on women-specific government schemes and grants",
      "Ivy marketplace for showcasing women-led products",
    ],
    eligibility: [
      "Women entrepreneurs or aspiring women business owners in India",
      "Women-led startups and MSMEs",
      "No age or income restriction for platform registration",
      "Valid email and mobile for account creation",
    ],
    documents: [
      "Aadhaar card",
      "Business registration proof if existing enterprise",
      "Profile photograph",
      "Brief business description",
    ],
    deadline: "2026-10-31",
    amount: "Access to schemes up to ₹1 crore+",
    location: "Pan India",
    officialUrl: "https://wep.gov.in",
    verified: true,
    tags: ["women", "entrepreneurship", "WEP", "NITI Aayog", "mentorship"],
    applicationSteps: [
      "Register on wep.gov.in with email and mobile verification",
      "Complete entrepreneur profile with business details",
      "Explore Ivy marketplace and mentorship programs",
      "Apply to relevant scheme listings on the platform",
      "Connect with mentors and investors through WEP networking events",
    ],
    commonMistakes: [
      "Incomplete profile reducing visibility to mentors and investors",
      "Not exploring linked schemes like Stand-Up India or MUDRA via WEP",
      "Ignoring WEP newsletters for funding opportunity announcements",
    ],
    faqs: [
      {
        question: "Does WEP provide direct funding?",
        answer:
          "WEP itself is an aggregator and support platform; direct funding comes through linked government schemes like Stand-Up India, MUDRA, and Startup India accessed via the portal.",
      },
    ],
    publishedAt: "2026-06-01",
  },
  {
    id: "mahila-samman-certificate",
    title: "Mahila Samman Savings Certificate",
    organization: "Ministry of Finance, Department of Economic Affairs",
    category: "Women Scheme",
    description:
      "Two-year small savings scheme exclusively for women and girls offering attractive fixed returns. Available through post offices and authorized banks for a limited period.",
    benefits: [
      "Interest rate of 7.5% per annum compounded quarterly",
      "Maximum deposit of ₹2 lakh per account",
      "Maturity period of 2 years",
      "Partial withdrawal allowed after 1 year",
    ],
    eligibility: [
      "Women and girl children only",
      "Indian resident",
      "Minimum deposit of ₹1,000 in multiples of ₹100",
      "Maximum single deposit of ₹2 lakh per account holder",
    ],
    documents: [
      "Aadhaar card",
      "PAN card (for deposits above ₹50,000)",
      "Passport-size photograph",
      "KYC documents as per post office or bank requirements",
    ],
    deadline: "2026-11-07",
    amount: "7.5% p.a. on up to ₹2 lakh",
    location: "Pan India",
    officialUrl: "https://www.indiapost.gov.in",
    verified: true,
    tags: ["women", "savings", "post-office", "fixed-return", "Mahila Samman"],
    applicationSteps: [
      "Visit nearest post office or authorized bank branch",
      "Fill Mahila Samman Savings Certificate application form",
      "Submit KYC documents and deposit amount (cash, cheque, or transfer)",
      "Receive certificate with account number and maturity date",
      "Collect maturity amount or opt for partial withdrawal after 1 year",
    ],
    commonMistakes: [
      "Exceeding ₹2 lakh deposit limit per account holder",
      "Attempting premature full withdrawal before 1 year (not permitted)",
      "Not carrying PAN for deposits above ₹50,000",
    ],
    faqs: [
      {
        question: "Can a guardian open Mahila Samman for a minor girl?",
        answer:
          "Yes. A guardian can open the account on behalf of a minor girl child with appropriate KYC documentation.",
      },
    ],
    publishedAt: "2026-06-01",
  },
  {
    id: "pm-kisan",
    title: "PM-KISAN (Pradhan Mantri Kisan Samman Nidhi)",
    organization: "Ministry of Agriculture & Farmers Welfare",
    category: "Farmer Scheme",
    description:
      "Central sector scheme providing income support of ₹6,000 per year in three equal installments to all landholding farmer families across India for agricultural and household needs.",
    benefits: [
      "₹6,000 per year in three installments of ₹2,000 each",
      "Direct Benefit Transfer to bank account",
      "No middlemen or state-level deductions",
      "Covers all landholding farmer families irrespective of land size",
    ],
    eligibility: [
      "Landholding farmer family with cultivable land in their name",
      "Valid bank account linked to Aadhaar",
      "Excludes institutional landholders, government employees, and income tax payers",
      "Farmer must be registered on PM-KISAN portal",
    ],
    documents: [
      "Aadhaar card",
      "Land ownership or cultivation records",
      "Bank passbook or account details",
      "Mobile number linked to Aadhaar",
    ],
    deadline: "2026-11-15",
    amount: "₹6,000/year",
    location: "Pan India",
    officialUrl: "https://pmkisan.gov.in",
    verified: true,
    tags: ["farmer", "PM-KISAN", "agriculture", "DBT", "income-support"],
    applicationSteps: [
      "Visit pmkisan.gov.in or nearest agriculture office",
      "Register with Aadhaar, land records, and bank details",
      "Village patwari or local revenue officer verifies land records",
      "State government approves and forwards to central DBT system",
      "Receive ₹2,000 installments every four months in bank account",
    ],
    commonMistakes: [
      "Bank account not linked to Aadhaar causing payment failure",
      "Incorrect land record details leading to verification rejection",
      "Not updating eKYC when Aadhaar or bank details change",
    ],
    faqs: [
      {
        question: "How do I check PM-KISAN payment status?",
        answer:
          "Use the 'Know Your Status' feature on pmkisan.gov.in by entering Aadhaar, bank account, or mobile number to track installment status.",
      },
      {
        question: "Are tenant farmers eligible?",
        answer:
          "PM-KISAN is for landholding farmers; tenant farmers without land ownership records are generally not eligible unless state-specific provisions apply.",
      },
    ],
    publishedAt: "2026-06-01",
  },
  {
    id: "pm-fasal-bima",
    title: "Pradhan Mantri Fasal Bima Yojana (PMFBY)",
    organization: "Ministry of Agriculture & Farmers Welfare",
    category: "Farmer Scheme",
    description:
      "Comprehensive crop insurance scheme protecting farmers against crop loss due to natural calamities, pests, and diseases. Farmers pay low premium with government subsidy on balance.",
    benefits: [
      "Coverage for food crops, oilseeds, and annual commercial crops",
      "Farmer premium: 2% for Kharif, 1.5% for Rabi, 5% for commercial crops",
      "Claim settlement based on crop cutting experiments or weather indices",
      "Use of technology (satellite, drones) for faster assessment",
    ],
    eligibility: [
      "All farmers growing notified crops in notified areas",
      "Compulsory for loanee farmers; voluntary for non-loanee farmers",
      "Crop sown in declared insurance unit area",
      "Enrollment within cutoff date for each crop season",
    ],
    documents: [
      "Aadhaar card",
      "Land records or tenancy certificate",
      "Bank account details",
      "Sowing certificate from patwari or agriculture officer",
      "Crop loan details if loanee farmer",
    ],
    deadline: "2026-11-22",
    amount: "Sum insured up to full cost of cultivation",
    location: "Pan India",
    officialUrl: "https://pmfby.gov.in",
    verified: true,
    tags: ["farmer", "crop-insurance", "PMFBY", "agriculture", "risk-cover"],
    applicationSteps: [
      "Enroll through bank (loanee farmers) or CSC, agriculture office, or online portal",
      "Select notified crop and insurance unit for the season",
      "Pay farmer share of premium before cutoff date",
      "Report crop loss within 72 hours of calamity to agriculture office",
      "Receive claim amount in bank account after assessment",
    ],
    commonMistakes: [
      "Missing enrollment deadline for the crop season",
      "Not reporting crop loss within 72-hour window",
      "Enrolling for non-notified crops in the area",
    ],
    faqs: [
      {
        question: "What perils are covered under PMFBY?",
        answer:
          "Coverage includes drought, flood, hailstorm, cyclone, pest and disease attack, and post-harvest losses for specified periods and crops.",
      },
    ],
    publishedAt: "2026-06-01",
  },
  {
    id: "nabard-kcc",
    title: "Kisan Credit Card (KCC) via NABARD",
    organization: "NABARD / Ministry of Agriculture & Farmers Welfare",
    category: "Farmer Scheme",
    description:
      "Revolving credit facility for farmers to meet short-term crop cultivation, post-harvest, and household consumption needs. Implemented through commercial banks, cooperatives, and RRBs with NABARD refinance.",
    benefits: [
      "Credit limit based on cropping pattern and land holding",
      "Interest subvention bringing effective rate to 4% for timely repayment",
      "Flexible drawdown and repayment aligned with harvest cycle",
      "Insurance and accident cover options linked to KCC",
    ],
    eligibility: [
      "Farmers, tenant farmers, oral lessees, and sharecroppers",
      "Self-help groups and joint liability groups of farmers",
      "Engaged in agriculture or allied activities (fisheries, animal husbandry)",
      "Satisfactory credit history or new borrowers with land proof",
    ],
    documents: [
      "Aadhaar card and PAN",
      "Land ownership or tenancy records",
      "Crop details and area under cultivation",
      "Bank account passbook",
      "Passport-size photograph",
    ],
    deadline: "2026-11-30",
    amount: "Based on scale of finance (typically ₹1–3 lakh+)",
    location: "Pan India",
    officialUrl: "https://www.nabard.org",
    verified: true,
    tags: ["farmer", "KCC", "NABARD", "credit", "agriculture-loan"],
    applicationSteps: [
      "Visit nearest bank branch (commercial, cooperative, or RRB)",
      "Fill Kisan Credit Card application with land and crop details",
      "Submit land records and identity documents",
      "Bank assesses credit limit based on scale of finance for crops",
      "Receive KCC card and operate account for crop and household needs",
    ],
    commonMistakes: [
      "Not repaying within due date and losing interest subvention benefit",
      "Understating cultivated area leading to insufficient credit limit",
      "Using KCC funds for non-agricultural purposes",
    ],
    faqs: [
      {
        question: "What is the interest rate on KCC?",
        answer:
          "With interest subvention and prompt repayment incentive, effective interest rate can be as low as 4% per annum on short-term crop loans up to ₹3 lakh.",
      },
    ],
    publishedAt: "2026-06-01",
  },
  {
    id: "soil-health-card",
    title: "Soil Health Card Scheme",
    organization: "Ministry of Agriculture & Farmers Welfare",
    category: "Farmer Scheme",
    description:
      "Provides farmers with soil health cards containing crop-wise nutrient recommendations based on soil test results. Promotes balanced fertilizer use and improved soil fertility.",
    benefits: [
      "Free or subsidized soil testing at government labs",
      "Customized fertilizer recommendations per crop and soil type",
      "Improved crop yield and reduced input costs",
      "Updated card every 2 years for each land holding",
    ],
    eligibility: [
      "All farmers with cultivable land",
      "Farmers in villages covered under soil testing campaign",
      "No income or land size restriction",
      "Registration through agriculture department or Krishi Vigyan Kendra",
    ],
    documents: [
      "Aadhaar card",
      "Land records or Khasra/Khatauni number",
      "Mobile number",
      "Soil sample collected from field as per guidelines",
    ],
    deadline: "2026-12-05",
    amount: "Free soil testing",
    location: "Pan India",
    officialUrl: "https://soilhealth.dac.gov.in",
    verified: true,
    tags: ["farmer", "soil-health", "agriculture", "fertilizer", "yield"],
    applicationSteps: [
      "Contact local agriculture officer or Krishi Vigyan Kendra",
      "Collect soil sample from field following prescribed depth and mixing method",
      "Submit sample with land details at designated soil testing lab",
      "Receive Soil Health Card with nutrient status and recommendations",
      "Apply fertilizers as per card recommendations for next crop season",
    ],
    commonMistakes: [
      "Collecting soil sample from wrong depth or single spot only",
      "Ignoring micronutrient recommendations on the card",
      "Not updating soil health card after 2 years",
    ],
    faqs: [
      {
        question: "How often should I get soil tested?",
        answer:
          "Government recommends soil testing and updated Soil Health Card every 2 years for each land holding.",
      },
    ],
    publishedAt: "2026-06-01",
  },
  {
    id: "pmjay",
    title: "Ayushman Bharat – Pradhan Mantri Jan Arogya Yojana (PM-JAY)",
    organization: "National Health Authority, Ministry of Health & Family Welfare",
    category: "Healthcare",
    description:
      "World's largest government-funded health assurance scheme providing annual hospitalization cover of ₹5 lakh per family for secondary and tertiary care to economically vulnerable families.",
    benefits: [
      "Health cover of ₹5 lakh per family per year",
      "Covers 1,900+ treatment procedures across specialties",
      "Cashless treatment at empanelled public and private hospitals",
      "No cap on family size or age of members",
    ],
    eligibility: [
      "Families identified per SECC 2011 deprivation criteria in rural areas",
      "11 occupational categories of urban workers in designated categories",
      "Verify eligibility using Aadhaar or ration card on PM-JAY portal",
      "Not applicable to existing central government health scheme beneficiaries",
    ],
    documents: [
      "Aadhaar card",
      "Ration card or SECC reference number",
      "Mobile number for OTP verification",
      "Family identification as per SECC database",
    ],
    deadline: "2026-12-10",
    amount: "Up to ₹5 lakh/family/year",
    location: "Pan India",
    officialUrl: "https://pmjay.gov.in",
    verified: true,
    tags: ["healthcare", "PM-JAY", "Ayushman Bharat", "insurance", "hospital"],
    applicationSteps: [
      "Check family eligibility on pmjay.gov.in or Ayushman app using Aadhaar",
      "Visit Ayushman Mitra at empanelled hospital for e-card generation",
      "Receive PM-JAY Golden Card with family coverage details",
      "Present card at empanelled hospital for cashless treatment",
      "Hospital submits claim to NHA for reimbursement under scheme",
    ],
    commonMistakes: [
      "Assuming all citizens are covered (only SECC-identified families)",
      "Seeking treatment at non-empanelled hospitals expecting cashless cover",
      "Not verifying updated family list on PM-JAY portal before hospitalization",
    ],
    faqs: [
      {
        question: "How do I check if my family is eligible?",
        answer:
          "Visit pmjay.gov.in, use the 'Am I Eligible' feature, and search by mobile number, ration card, or SECC ID to verify coverage.",
      },
      {
        question: "Is PM-JAY available for senior citizens above 70?",
        answer:
          "A separate Ayushman Vaya Vandana Card provides ₹5 lakh cover for all citizens aged 70+, regardless of SECC status, as announced in recent budget provisions.",
      },
    ],
    publishedAt: "2026-06-01",
  },
  {
    id: "ab-hwcs",
    title: "Ayushman Bharat Health Infrastructure Mission (PM-ABHIM)",
    organization: "Ministry of Health & Family Welfare",
    category: "Healthcare",
    description:
      "Centrally sponsored scheme strengthening health infrastructure through Health and Wellness Centres, district hospitals, and critical care blocks. Improves access to primary and secondary healthcare.",
    benefits: [
      "Establishment of 1.5 lakh Health and Wellness Centres (HWCs) by upgrading sub-centres",
      "Strengthening district hospitals and critical care blocks",
      "Free essential diagnostics and medicines at HWCs under AB-HWC",
      "Teleconsultation and e-health records integration",
    ],
    eligibility: [
      "All citizens accessing services at upgraded Health and Wellness Centres",
      "Beneficiaries of Ayushman Bharat and National Health Mission services",
      "No separate enrollment required for HWC primary care services",
      "PM-JAY eligibility applies separately for hospitalization cover",
    ],
    documents: [
      "Aadhaar card for registration at HWC",
      "Ayushman Bharat card if applicable",
      "Ration card or address proof",
      "Previous medical records if any",
    ],
    deadline: "2026-12-15",
    amount: "Free primary care at HWCs",
    location: "Pan India",
    officialUrl: "https://ab-hwc.nhp.gov.in",
    verified: true,
    tags: ["healthcare", "AB-HWC", "primary-care", "wellness-centre", "infrastructure"],
    applicationSteps: [
      "Locate nearest Health and Wellness Centre on ab-hwc.nhp.gov.in",
      "Register with Aadhaar at HWC for AB-HWC services",
      "Access free screening for NCDs, maternal and child health services",
      "Receive essential medicines and diagnostics as prescribed",
      "Get referral to district hospital for secondary care if needed",
    ],
    commonMistakes: [
      "Confusing HWC primary care with PM-JAY hospitalization benefits",
      "Not carrying Aadhaar for HWC registration and teleconsultation",
      "Skipping follow-up visits for chronic disease management at HWC",
    ],
    faqs: [
      {
        question: "What services are free at Health and Wellness Centres?",
        answer:
          "HWCs provide free services including NCD screening, maternal care, immunization, essential drugs, diagnostics, and teleconsultation under the AB-HWC package.",
      },
    ],
    publishedAt: "2026-06-01",
  },
  {
    id: "pmay-urban",
    title: "Pradhan Mantri Awas Yojana – Urban (PMAY-U)",
    organization: "Ministry of Housing and Urban Affairs",
    category: "Housing",
    description:
      "Credit-linked subsidy scheme for economically weaker sections to purchase or construct pucca houses in urban areas. Provides interest subsidy on home loans through participating banks.",
    benefits: [
      "Interest subsidy of 6.5% on home loans up to ₹6 lakh for EWS/LIG",
      "Maximum subsidy amount of ₹2.67 lakh over loan tenure",
      "Affordable housing in partnership with private developers",
      "Beneficiary-led individual house construction support",
    ],
    eligibility: [
      "Economically Weaker Section (EWS): annual income up to ₹3 lakh",
      "Low Income Group (LIG): annual income ₹3–6 lakh",
      "Middle Income Group (MIG): income up to ₹18 lakh (separate CLSS norms)",
      "Beneficiary family should not own a pucca house anywhere in India",
    ],
    documents: [
      "Aadhaar card of all family members",
      "Income certificate or self-declaration",
      "Property documents or allotment letter",
      "Bank loan sanction letter",
      "Affidavit declaring no existing pucca house",
    ],
    deadline: "2026-12-20",
    amount: "Subsidy up to ₹2.67 lakh",
    location: "Pan India (urban areas)",
    officialUrl: "https://pmay-urban.gov.in",
    verified: true,
    tags: ["housing", "PMAY", "urban", "home-loan", "subsidy", "EWS", "LIG"],
    applicationSteps: [
      "Apply online at pmay-urban.gov.in or through ULB",
      "Select component: Beneficiary-led construction, AHP, or CLSS",
      "Submit income proof and no-pucca-house affidavit",
      "For CLSS, apply home loan at participating bank or HFC",
      "Receive interest subsidy credited to loan account by lending institution",
    ],
    commonMistakes: [
      "Applying when family already owns a pucca house (ineligible)",
      "Not applying through PMAY-ULB portal before loan disbursement for CLSS",
      "Incorrect income category selection affecting subsidy amount",
    ],
    faqs: [
      {
        question: "Can I avail PMAY-U if I already have a home loan?",
        answer:
          "If the loan was sanctioned after PMAY guidelines and you meet eligibility, CLSS subsidy can be claimed through your lending institution before subsidy cap is exhausted.",
      },
    ],
    publishedAt: "2026-06-01",
  },
  {
    id: "pmay-gramin",
    title: "Pradhan Mantri Awas Yojana – Gramin (PMAY-G)",
    organization: "Ministry of Rural Development",
    category: "Housing",
    description:
      "Rural housing scheme providing financial assistance to homeless and those living in kutcha or dilapidated houses. Aims to provide pucca houses with basic amenities to rural households.",
    benefits: [
      "Financial assistance of ₹1.20 lakh in plain areas",
      "₹1.30 lakh in hilly, difficult, and IAP districts",
      "Additional ₹12,000 for toilet construction under SBM-G convergence",
      "MGNREGA wage component for unskilled labor up to 90/95 days",
    ],
    eligibility: [
      "Households without pucca house or living in kutcha/dilapidated house",
      "Selected from SECC 2011 data with automatic inclusion and exclusion criteria",
      "Priority to SC/ST, minorities, and persons with disabilities",
      "Beneficiary must own or possess land for house construction",
    ],
    documents: [
      "Aadhaar card",
      "SECC 2011 registration or state BPL list inclusion proof",
      "Land ownership or NOC from landowner",
      "Bank or post office account for DBT",
      "Job card under MGNREGA if applicable",
    ],
    deadline: "2026-12-28",
    amount: "₹1.20–1.30 lakh",
    location: "Pan India (rural areas)",
    officialUrl: "https://pmayg.nic.in",
    verified: true,
    tags: ["housing", "PMAY-G", "rural", "pucca-house", "Gramin"],
    applicationSteps: [
      "Verify inclusion in PMAY-G beneficiary list via pmayg.nic.in",
      "Gram Sabha validates and prioritizes beneficiaries",
      "Register with Aadhaar and bank account on AwaasSoft portal",
      "Construct house as per approved design and technical norms",
      "Receive installment-based DBT upon geo-tagged progress verification",
    ],
    commonMistakes: [
      "Starting construction before sanction and geo-tagging of site",
      "Not meeting minimum room size and structural safety norms",
      "Bank account not linked to Aadhaar causing installment delay",
    ],
    faqs: [
      {
        question: "How are PMAY-G beneficiaries selected?",
        answer:
          "Selection uses SECC 2011 data with automatic exclusion (pucca house owners, government employees, etc.) and inclusion (homeless, kutcha house) criteria validated by Gram Sabha.",
      },
    ],
    publishedAt: "2026-06-01",
  },
  {
    id: "swayam",
    title: "SWAYAM – Free Online Courses",
    organization: "Ministry of Education, MHRD (now MoE)",
    category: "Education",
    description:
      "Study Webs of Active-Learning for Young Aspiring Minds platform offering free MOOCs from top Indian institutions. Courses span school, undergraduate, postgraduate, and skill-based learning.",
    benefits: [
      "Free access to 1,000+ courses from IITs, IISc, UGC, and NPTEL",
      "Credit transfer to degree programs at partner universities",
      "Certificates upon successful completion and proctored exam",
      "Learn at own pace with video lectures and assignments",
    ],
    eligibility: [
      "Open to all learners in India and abroad",
      "No age or qualification bar for enrollment",
      "Credit transfer requires enrollment in partner university degree program",
      "Proctored certification exam may have fee (typically ₹1,000)",
    ],
    documents: [
      "Email ID for registration",
      "Aadhaar for proctored certification exam",
      "University enrollment proof for credit transfer",
      "Photo ID for exam center verification",
    ],
    deadline: "2026-12-31",
    amount: "Free (exam fee ~₹1,000 for certificate)",
    location: "Pan India",
    officialUrl: "https://swayam.gov.in",
    verified: true,
    tags: ["education", "MOOC", "online-course", "NPTEL", "free-learning"],
    applicationSteps: [
      "Register on swayam.gov.in with email and password",
      "Browse and enroll in courses by start date",
      "Complete video lectures, quizzes, and assignments",
      "Register for proctored in-person exam if seeking certificate",
      "Apply for credit transfer through your university's academic cell",
    ],
    commonMistakes: [
      "Missing proctored exam registration deadline",
      "Assuming all courses offer free certificates without exam fee",
      "Not checking if university accepts SWAYAM credits before enrolling",
    ],
    faqs: [
      {
        question: "Can SWAYAM courses count toward my degree?",
        answer:
          "Yes. UGC allows up to 40% credit transfer from SWAYAM courses in partner universities, subject to institutional approval and exam clearance.",
      },
    ],
    publishedAt: "2026-06-01",
  },
  {
    id: "khelo-india",
    title: "Khelo India Scheme",
    organization: "Ministry of Youth Affairs and Sports",
    category: "Education",
    description:
      "National program for development of sports providing infrastructure, talent identification, scholarships, and competitive exposure to young athletes across Olympic and Paralympic disciplines.",
    benefits: [
      "Khelo India Youth Games and University Games participation",
      "Annual scholarship of ₹6.28 lakh for selected Khelo India athletes",
      "Sports infrastructure grants to schools and academies",
      "Talent identification through Khelo India centres",
    ],
    eligibility: [
      "Young athletes in age group 10–18 for youth games (varies by event)",
      "University students for Khelo India University Games",
      "State nomination required for national-level competitions",
      "Athletes in Olympic, Asian Games, and Commonwealth Games disciplines",
    ],
    documents: [
      "Aadhaar card",
      "Age proof (birth certificate or school certificate)",
      "Sports achievement certificates",
      "Medical fitness certificate",
      "State sports federation nomination letter",
    ],
    deadline: "2026-08-10",
    amount: "Scholarship up to ₹6.28 lakh/year",
    location: "Pan India",
    officialUrl: "https://kheloindia.gov.in",
    verified: true,
    tags: ["sports", "Khelo India", "athlete", "scholarship", "youth-games"],
    applicationSteps: [
      "Register on Khelo India portal or through state sports authority",
      "Participate in district and state-level qualifying competitions",
      "Get nominated by state for Khelo India Youth Games",
      "Compete at national level for talent identification",
      "Selected athletes receive scholarship and training support",
    ],
    commonMistakes: [
      "Missing state-level qualification events for national games",
      "Submitting incorrect age proof for age-group categories",
      "Not maintaining medical fitness certification for competition",
    ],
    faqs: [
      {
        question: "What is the Khelo India scholarship amount?",
        answer:
          "Selected athletes receive an out-of-pocket allowance of ₹6.28 lakh per annum along with training, kit, and competition support at accredited academies.",
      },
    ],
    publishedAt: "2026-06-01",
  },
  {
    id: "sukanya-samriddhi",
    title: "Sukanya Samriddhi Yojana (SSY)",
    organization: "Ministry of Finance, Department of Economic Affairs",
    category: "Welfare",
    description:
      "Small savings scheme for parents of girl children below 10 years. Offers high interest rates and tax benefits under Section 80C to build corpus for education and marriage expenses.",
    benefits: [
      "Attractive interest rate set by government (revised quarterly)",
      "Tax deduction up to ₹1.5 lakh under Section 80C",
      "Interest and maturity amount fully tax-exempt",
      "Account matures when girl turns 21 or on marriage after 18",
    ],
    eligibility: [
      "Girl child below 10 years of age at time of account opening",
      "Maximum two accounts per family (three for twins/triplets)",
      "Account opened by parent or legal guardian",
      "Indian resident girl child only",
    ],
    documents: [
      "Birth certificate of girl child",
      "Aadhaar of parent/guardian and child",
      "Address proof of guardian",
      "Passport-size photographs",
      "KYC documents at post office or authorized bank",
    ],
    deadline: "2026-09-08",
    amount: "Min ₹250/year, max ₹1.5 lakh/year",
    location: "Pan India",
    officialUrl: "https://www.indiapost.gov.in",
    verified: true,
    tags: ["welfare", "girl-child", "savings", "SSY", "tax-benefit"],
    applicationSteps: [
      "Visit post office or authorized bank with girl child's birth certificate",
      "Fill SSY account opening form with guardian details",
      "Deposit minimum ₹250 to activate account",
      "Continue annual deposits up to ₹1.5 lakh until maturity",
      "Partial withdrawal allowed for higher education after girl turns 18",
    ],
    commonMistakes: [
      "Opening account after girl child turns 10 (not permitted)",
      "Missing minimum annual deposit of ₹250 (account becomes dormant)",
      "Exceeding two accounts per family limit",
    ],
    faqs: [
      {
        question: "When can I withdraw from Sukanya Samriddhi?",
        answer:
          "Up to 50% withdrawal is allowed for higher education after the girl turns 18. Full maturity withdrawal is at 21 years or on marriage after 18 with account closure.",
      },
    ],
    publishedAt: "2026-06-01",
  },
  {
    id: "eshram",
    title: "e-Shram – Unorganised Workers Registration",
    organization: "Ministry of Labour & Employment",
    category: "Welfare",
    description:
      "National database registering unorganised workers to deliver social security benefits including accident insurance, pension, and access to welfare schemes through a universal account number (UAN).",
    benefits: [
      "Free accident insurance cover of ₹2 lakh under PM-SYM",
      "Access to social security and welfare schemes via UAN",
      "Portable identity across states and employers",
      "Priority for skill training and employment programs",
    ],
    eligibility: [
      "Unorganised worker aged 16–59 years",
      "Not member of EPFO, ESIC, or government pension scheme",
      "Not income tax payer",
      "Engaged in unorganised sector occupation (construction, domestic work, gig, etc.)",
    ],
    documents: [
      "Aadhaar card",
      "Bank account details",
      "Mobile number linked to Aadhaar",
      "Occupation and skill details",
      "Passport-size photograph",
    ],
    deadline: "2026-10-08",
    amount: "₹2 lakh accident insurance",
    location: "Pan India",
    officialUrl: "https://eshram.gov.in",
    verified: true,
    tags: ["welfare", "e-Shram", "unorganised-worker", "UAN", "insurance"],
    applicationSteps: [
      "Visit eshram.gov.in or nearest CSC for registration",
      "Enter Aadhaar and verify with OTP",
      "Fill occupation, skill, and bank account details",
      "Receive e-Shram card with 12-digit UAN instantly",
      "Use UAN to access linked welfare schemes and insurance benefits",
    ],
    commonMistakes: [
      "Registering while being EPFO or ESIC member (ineligible)",
      "Providing incorrect occupation category",
      "Not updating bank details when account changes",
    ],
    faqs: [
      {
        question: "Is e-Shram registration free?",
        answer:
          "Yes. Registration on eshram.gov.in is completely free. Workers receive UAN and accident insurance without any registration fee.",
      },
    ],
    publishedAt: "2026-06-01",
  },
  {
    id: "pmkvy",
    title: "Pradhan Mantri Kaushal Vikas Yojana (PMKVY)",
    organization: "Ministry of Skill Development and Entrepreneurship, NSDC",
    category: "Skill Development",
    description:
      "Flagship skill certification scheme providing free short-term training aligned to National Skills Qualification Framework. Enables youth to gain industry-relevant skills and placement assistance.",
    benefits: [
      "Free skill training at NSDC-affiliated training centres",
      "Government-recognized certificate upon assessment",
      "Placement assistance and entrepreneurship guidance",
      "Training aligned to industry job roles with monetary reward on certification",
    ],
    eligibility: [
      "Indian citizen aged 15–45 years (age relaxation for reserved categories)",
      "School dropout or unemployed youth seeking skill certification",
      "Not enrolled in any other government skill training program simultaneously",
      "Valid Aadhaar-linked bank account for reward disbursement",
    ],
    documents: [
      "Aadhaar card",
      "Bank account passbook",
      "Educational certificates",
      "Passport-size photograph",
      "Identity proof",
    ],
    deadline: "2026-11-10",
    amount: "Free training + certification reward",
    location: "Pan India",
    officialUrl: "https://www.pmkvyofficial.org",
    verified: true,
    tags: ["skill", "PMKVY", "NSDC", "training", "certification", "employment"],
    applicationSteps: [
      "Find nearest PMKVY training centre on pmkvyofficial.org",
      "Enroll in job role matching your interest and qualification",
      "Complete training hours as per Qualification Pack requirements",
      "Appear for third-party assessment by SSC",
      "Receive certificate and placement support upon successful assessment",
    ],
    commonMistakes: [
      "Enrolling in non-NSDC-affiliated centres claiming PMKVY benefits",
      "Missing assessment dates after completing training",
      "Providing bank account not linked to Aadhaar for reward payment",
    ],
    faqs: [
      {
        question: "Is PMKVY training really free?",
        answer:
          "Yes. Training cost is borne by the government through NSDC. Certified candidates may also receive monetary reward as per scheme guidelines.",
      },
    ],
    publishedAt: "2026-06-01",
  },
  {
    id: "naps-apprenticeship",
    title: "National Apprenticeship Promotion Scheme (NAPS)",
    organization: "Ministry of Skill Development and Entrepreneurship",
    category: "Skill Development",
    description:
      "Promotes apprenticeship training in industries by sharing training costs with employers. Provides stipend support and formal certification for youth gaining on-the-job skills.",
    benefits: [
      "Stipend support with government sharing up to 25% of prescribed stipend",
      "Formal apprenticeship contract and completion certificate",
      "Exposure to industry-standard practices and equipment",
      "Enhanced employability and potential permanent job offer",
    ],
    eligibility: [
      "Indian citizen aged 14–35 years (varies by trade)",
      "Minimum educational qualification as per trade requirement",
      "Not currently employed full-time elsewhere",
      "Medical fitness as per apprenticeship trade norms",
    ],
    documents: [
      "Aadhaar card",
      "Educational certificates",
      "Bank account details",
      "Medical fitness certificate",
      "Passport-size photograph",
    ],
    deadline: "2026-12-12",
    amount: "Stipend ₹5,000–9,000/month (varies)",
    location: "Pan India",
    officialUrl: "https://www.apprenticeshipindia.gov.in",
    verified: true,
    tags: ["apprenticeship", "NAPS", "skill", "on-job-training", "stipend"],
    applicationSteps: [
      "Register on apprenticeshipindia.gov.in as apprentice candidate",
      "Browse and apply to apprenticeship openings posted by employers",
      "Complete contract signing with establishment on portal",
      "Undergo on-the-job training for 6–36 months as per trade",
      "Receive completion certificate and stipend via DBT upon successful completion",
    ],
    commonMistakes: [
      "Not signing formal apprenticeship contract on portal",
      "Leaving apprenticeship before contract period without proper exit",
      "Applying to trades without meeting minimum educational qualification",
    ],
    faqs: [
      {
        question: "What is the stipend under NAPS?",
        answer:
          "Stipend is set by employer as per Apprentices Act norms; government reimburses up to 25% of stipend subject to a monthly cap defined under NAPS guidelines.",
      },
    ],
    publishedAt: "2026-06-01",
  },
  {
    id: "digilocker-digital-india",
    title: "DigiLocker – Digital Document Wallet",
    organization: "Ministry of Electronics & IT, Digital India",
    category: "Skill Development",
    description:
      "Cloud-based platform for issuance and verification of documents and certificates in digital format. Reduces dependency on physical documents for education, employment, and government services.",
    benefits: [
      "Free secure storage for government-issued digital documents",
      "Aadhaar-linked verification accepted by government agencies",
      "Integration with CBSE, universities, RTO, and income tax departments",
      "Share documents via URI link without physical copies",
    ],
    eligibility: [
      "Indian citizen with valid Aadhaar number",
      "Mobile number linked to Aadhaar for OTP verification",
      "Open to students, job seekers, and all citizens",
      "No age restriction",
    ],
    documents: [
      "Aadhaar card",
      "Mobile number linked to Aadhaar",
      "Email ID for account recovery",
    ],
    deadline: "2026-08-20",
    amount: "Free",
    location: "Pan India",
    officialUrl: "https://www.digilocker.gov.in",
    verified: true,
    tags: ["DigiLocker", "Digital India", "documents", "e-governance", "Aadhaar"],
    applicationSteps: [
      "Download DigiLocker app or visit digilocker.gov.in",
      "Sign up using Aadhaar and verify with mobile OTP",
      "Fetch issued documents from integrated departments (CBSE, UIDAI, etc.)",
      "Upload self-attested documents in 'Uploaded Documents' section",
      "Share document URI with employers or institutions for verification",
    ],
    commonMistakes: [
      "Using mobile number not linked to Aadhaar for registration",
      "Uploading low-quality scans that fail verification",
      "Sharing DigiLocker PIN or OTP with unauthorized persons",
    ],
    faqs: [
      {
        question: "Are DigiLocker documents legally valid?",
        answer:
          "Yes. Documents issued by registered issuers on DigiLocker are deemed legally equivalent to original physical documents under the IT Act and government notifications.",
      },
    ],
    publishedAt: "2026-06-01",
  },
  {
    id: "pm-vishwakarma",
    title: "PM Vishwakarma Scheme",
    organization: "Ministry of Micro, Small and Medium Enterprises",
    category: "Skill Development",
    description:
      "Supports traditional artisans and craftspeople (carpenters, blacksmiths, potters, tailors, etc.) with skill upgradation, toolkit incentives, credit support, and market linkages.",
    benefits: [
      "PM Vishwakarma certificate and ID card",
      "Skill training with stipend of ₹500 per day",
      "Toolkit incentive of up to ₹15,000",
      "Collateral-free enterprise development loans up to ₹2 lakh at concessional rate",
    ],
    eligibility: [
      "Engaged in 18 designated family-based traditional trades",
      "Age 18 years and above",
      "Working with hands and tools in unorganized sector",
      "Not availing benefits under other MSME schemes for same activity",
    ],
    documents: [
      "Aadhaar card",
      "Bank account details",
      "Proof of engagement in listed trade",
      "Mobile number",
      "Passport-size photograph",
    ],
    deadline: "2026-09-18",
    amount: "Toolkit ₹15,000 + loan up to ₹2 lakh",
    location: "Pan India",
    officialUrl: "https://pmvishwakarma.gov.in",
    verified: true,
    tags: ["artisan", "craftsman", "Vishwakarma", "MSME", "traditional-trade"],
    applicationSteps: [
      "Register on pmvishwakarma.gov.in with Aadhaar verification",
      "Select your traditional trade from 18 listed categories",
      "Complete skill assessment and basic training module",
      "Receive toolkit incentive upon training completion",
      "Apply for enterprise development loan through participating banks",
    ],
    commonMistakes: [
      "Selecting trade category that does not match actual occupation",
      "Skipping mandatory skill training before toolkit disbursement",
      "Applying when already registered under overlapping MSME scheme",
    ],
    faqs: [
      {
        question: "Which trades are covered under PM Vishwakarma?",
        answer:
          "18 trades include carpenter, boat maker, armourer, blacksmith, hammer and tool kit maker, locksmith, goldsmith, potter, sculptor, stone breaker, cobbler, mason, basket maker, cooper, barber, garland maker, washerman, and tailor.",
      },
    ],
    publishedAt: "2026-06-01",
  },
  {
    id: "atal-pension-yojana",
    title: "Atal Pension Yojana (APY)",
    organization: "Ministry of Finance, PFRDA",
    category: "Welfare",
    description:
      "Government-backed pension scheme for workers in unorganised sector providing guaranteed minimum monthly pension after 60 years of age. Co-contribution from government for eligible subscribers.",
    benefits: [
      "Guaranteed pension of ₹1,000 to ₹5,000 per month after age 60",
      "Government co-contribution of 50% of subscriber contribution (up to ₹1,000/year) for 5 years",
      "Spouse receives pension after subscriber's death; nominee gets corpus",
      "Tax benefit under Section 80CCD(1) for contributions",
    ],
    eligibility: [
      "Indian citizen aged 18–40 years",
      "Savings bank account holder with Aadhaar-linked mobile",
      "Not income tax payer",
      "Not covered under any statutory social security scheme",
    ],
    documents: [
      "Aadhaar card",
      "Bank account details",
      "Mobile number",
      "Nominee details with Aadhaar",
    ],
    deadline: "2026-10-20",
    amount: "Pension ₹1,000–5,000/month after 60",
    location: "Pan India",
    officialUrl: "https://www.npscra.nsdl.co.in/apy",
    verified: true,
    tags: ["pension", "APY", "social-security", "unorganised-worker", "retirement"],
    applicationSteps: [
      "Visit bank or post office where you hold savings account",
      "Fill Atal Pension Yojana registration form with pension amount choice",
      "Authorize auto-debit for monthly, quarterly, or half-yearly contribution",
      "Receive PRAN (Pension Account Number) via SMS",
      "Continue contributions until age 60 to receive guaranteed pension",
    ],
    commonMistakes: [
      "Insufficient bank balance causing auto-debit failure and account default",
      "Subscribing after age 40 (not eligible for new enrollment)",
      "Not updating nominee details after life events",
    ],
    faqs: [
      {
        question: "What happens if I stop contributing to APY?",
        answer:
          "Account may be frozen or defaulted; partial withdrawal is not allowed before 60 except in terminal illness or death. Regular contributions are essential for guaranteed pension.",
      },
    ],
    publishedAt: "2026-06-01",
  },
  {
    id: "pm-svanidhi",
    title: "PM Street Vendor's AtmaNirbhar Nidhi (PM SVANidhi)",
    organization: "Ministry of Housing and Urban Affairs",
    category: "Welfare",
    description:
      "Micro-credit facility for street vendors to resume livelihoods with working capital loans. Provides collateral-free credit with interest subsidy for urban street vendors identified through survey.",
    benefits: [
      "First tranche loan of ₹10,000 with 7% interest subsidy",
      "Second loan of ₹20,000 upon timely repayment of first",
      "Third loan of ₹50,000 for established vendors",
      "Digital payment incentives for UPI transactions",
    ],
    eligibility: [
      "Street vendor with Certificate of Vending or Survey Reference Number",
      "Vending in urban area before March 24, 2020",
      "Not defaulter to any financial institution",
      "Possess Aadhaar and vending certificate from ULB survey",
    ],
    documents: [
      "Aadhaar card",
      "Certificate of Vending or Letter of Recommendation from ULB",
      "Bank account details",
      "Vending site photograph",
      "Mobile number",
    ],
    deadline: "2026-11-18",
    amount: "Up to ₹50,000 in tranches",
    location: "Pan India (urban areas)",
    officialUrl: "https://pmsvanidhi.mohua.gov.in",
    verified: true,
    tags: ["street-vendor", "PM SVANidhi", "micro-credit", "urban", "livelihood"],
    applicationSteps: [
      "Obtain vending certificate from urban local body survey",
      "Apply on pmsvanidhi.mohua.gov.in or through lending institution",
      "Submit vending proof and bank account for ₹10,000 first loan",
      "Repay first loan on time to unlock ₹20,000 second tranche",
      "Continue timely repayment for eligibility to ₹50,000 third loan",
    ],
    commonMistakes: [
      "Applying without ULB vending certificate or survey reference",
      "Missing repayment deadline and losing access to higher tranches",
      "Not linking loan account for interest subsidy credit",
    ],
    faqs: [
      {
        question: "Is PM SVANidhi only for existing vendors?",
        answer:
          "Yes. Scheme targets street vendors vending in urban areas before March 2020, identified through ULB-led survey and issued Certificate of Vending.",
      },
    ],
    publishedAt: "2026-06-01",
  },
  {
    id: "mgnrega",
    title: "Mahatma Gandhi National Rural Employment Guarantee Act (MGNREGA)",
    organization: "Ministry of Rural Development",
    category: "Welfare",
    description:
      "Legal guarantee of 100 days of wage employment per rural household per financial year for unskilled manual work. World's largest work guarantee programme for rural livelihood security.",
    benefits: [
      "100 days guaranteed wage employment per household per year",
      "Wages paid as per state-notified MGNREGA wage rate (₹220–370/day)",
      "Unemployment allowance if work not provided within 15 days of demand",
      "Works focused on water conservation, roads, and rural infrastructure",
    ],
    eligibility: [
      "Adult member of rural household willing to do unskilled manual work",
      "Resident of rural area in implementing gram panchayat",
      "Job card holder registered at local gram panchayat",
      "No restriction based on gender, caste, or religion",
    ],
    documents: [
      "Aadhaar card",
      "Passport-size photograph",
      "Address proof in rural area",
      "Bank or post office account for wage payment",
    ],
    deadline: "2026-12-22",
    amount: "100 days × state wage rate",
    location: "Pan India (rural areas)",
    officialUrl: "https://nrega.nic.in",
    verified: true,
    tags: ["MGNREGA", "employment", "rural", "wages", "job-guarantee"],
    applicationSteps: [
      "Apply for Job Card at gram panchayat with photograph and Aadhaar",
      "Submit written work demand application at gram panchayat",
      "Receive dated receipt; work must be provided within 15 days",
      "Mark attendance at work site using muster roll",
      "Wages credited to bank or post office account within 15 days of work period",
    ],
    commonMistakes: [
      "Not submitting formal written work demand (oral requests not valid)",
      "Job card not updated with new household members",
      "Not reporting delayed wage payments on MIS or grievance portal",
    ],
    faqs: [
      {
        question: "What is the current MGNREGA wage rate?",
        answer:
          "Wage rates vary by state and are revised annually. Check nrega.nic.in for the latest state-wise notified daily wage rate under MGNREGA.",
      },
    ],
    publishedAt: "2026-06-01",
  },
  {
    id: "jan-dhan-yojana",
    title: "Pradhan Mantri Jan Dhan Yojana (PMJDY)",
    organization: "Ministry of Finance, Department of Financial Services",
    category: "Welfare",
    description:
      "National mission for financial inclusion providing zero-balance bank accounts, RuPay debit card, accident insurance, and access to credit, pension, and insurance for unbanked households.",
    benefits: [
      "Zero-balance Basic Savings Bank Deposit Account",
      "RuPay debit card with accident insurance cover of ₹2 lakh",
      "Overdraft facility up to ₹10,000 after satisfactory account operation",
      "Direct Benefit Transfer for all government subsidies",
    ],
    eligibility: [
      "Indian citizen without existing bank account (or eligible for additional PMJDY account)",
      "Minimum age 10 years (minor accounts with guardian)",
      "Valid identity and address proof",
      "No minimum income requirement",
    ],
    documents: [
      "Aadhaar card (or other officially valid KYC document)",
      "Address proof if Aadhaar address differs",
      "Passport-size photograph",
      "Mobile number for account linking",
    ],
    deadline: "2026-09-12",
    amount: "₹2 lakh accident insurance + ₹10,000 OD",
    location: "Pan India",
    officialUrl: "https://pmjdy.gov.in",
    verified: true,
    tags: ["financial-inclusion", "Jan Dhan", "bank-account", "DBT", "insurance"],
    applicationSteps: [
      "Visit any bank branch or Business Correspondent with KYC documents",
      "Fill PMJDY account opening form",
      "Receive RuPay debit card and passbook",
      "Link Aadhaar and mobile for DBT and UPI services",
      "Apply for overdraft after 6 months of satisfactory account operation",
    ],
    commonMistakes: [
      "Letting account become dormant due to no transactions",
      "Not seeding Aadhaar for DBT causing subsidy payment failures",
      "Confusing PMJDY overdraft with automatic entitlement (bank discretion applies)",
    ],
    faqs: [
      {
        question: "Is PMJDY account really zero balance?",
        answer:
          "Yes. PMJDY accounts have no minimum balance requirement. However, regular transactions are needed to keep the account active and qualify for overdraft.",
      },
    ],
    publishedAt: "2026-06-01",
  },
  {
    id: "pm-kusum",
    title: "PM-KUSUM (Pradhan Mantri Kisan Urja Suraksha evam Utthaan Mahabhiyan)",
    organization: "Ministry of New and Renewable Energy",
    category: "Farmer Scheme",
    description:
      "Promotes solar energy use in agriculture through solar pumps, grid-connected solar power plants, and solarisation of existing grid-connected pumps. Reduces diesel dependence and increases farmer income.",
    benefits: [
      "Subsidy up to 60% on solar pump installation cost",
      "Farmer pays 10–40% depending on component; balance as bank loan",
      "Sell surplus solar power to DISCOM under Component B and C",
      "Reduced irrigation cost and diesel expenditure",
    ],
    eligibility: [
      "Farmers with valid land ownership or lease documents",
      "Existing grid-connected pump owners for solarisation (Component B)",
      "Farmers, cooperatives, and panchayats for standalone solar pumps (Component A)",
      "Compliance with state DISCOM and MNRE technical specifications",
    ],
    documents: [
      "Aadhaar card",
      "Land ownership or lease documents",
      "Existing electricity connection details (for solarisation)",
      "Bank account for subsidy and power sale proceeds",
      "Quotation from MNRE-approved vendor",
    ],
    deadline: "2026-08-25",
    amount: "Subsidy up to 60% of solar pump cost",
    location: "Pan India",
    officialUrl: "https://mnre.gov.in/solar/schemes",
    verified: true,
    tags: ["farmer", "solar", "PM-KUSUM", "renewable-energy", "irrigation"],
    applicationSteps: [
      "Check state-wise PM-KUSUM implementation on mnre.gov.in",
      "Apply through state renewable energy agency or DISCOM portal",
      "Select component (A: solar pumps, B: solarisation, C: grid-connected plants)",
      "Get installation from MNRE-listed vendor with approved specifications",
      "Receive subsidy disbursement after inspection and commissioning",
    ],
    commonMistakes: [
      "Purchasing solar pumps from non-MNRE-listed vendors (subsidy denied)",
      "Not completing DISCOM net-metering formalities for surplus power sale",
      "Applying without valid land or electricity connection documents",
    ],
    faqs: [
      {
        question: "What subsidy does a farmer get under PM-KUSUM?",
        answer:
          "For standalone solar pumps, central and state subsidies together can cover up to 60% of cost; farmer contributes 10% and remaining 30% may be financed as bank loan.",
      },
    ],
    publishedAt: "2026-06-01",
  },
];
